local t = require("tests.framework")
local Backend = require("fcs.io.backend")
local mocks = require("tests.mocks.peripherals")
t.test("setThruster on/off writes full/zero thrust to the bound peripheral", function()
  local th = mocks.thruster()
  local shim = mocks.shim({ thruster_1 = th })
  local cfg = { thrusters = { FL = "thruster_1" }, sensors = {}, bindings = {} }
  local b = Backend.new(shim, cfg)
  b:setThruster("FL", true);  t.near(th.thrust, 15, 1e-9)
  b:setThruster("FL", false); t.near(th.thrust, 0, 1e-9)
end)
t.test("setThruster on an unbound id is a harmless no-op", function()
  local b = Backend.new(mocks.shim({}), { thrusters = { FL = false }, sensors = {}, bindings = {} })
  b:setThruster("FL", true)   -- must not error
  t.truthy(true)
end)
t.test("liftIds returns the four lift ids", function()
  local b = Backend.new(mocks.shim({}), { thrusters = {}, sensors = {}, bindings = {} })
  t.eq(#b:liftIds(), 4)
end)
