-- tests/test_telemetry.lua
local t = require("tests.framework")
local telemetry = require("fcs.comms.telemetry")

t.test("tx stamps a monotonic seq and carries the snapshot", function()
  local tx = telemetry.Tx.new()
  local f1 = tx:frame({ alt = 10 })
  local f2 = tx:frame({ alt = 11 })
  t.eq(f1.k, "tel"); t.eq(f1.s.alt, 10)
  t.truthy(f2.seq > f1.seq, "seq increases")
end)

t.test("rx keeps the latest and rejects stale/duplicate", function()
  local tx, rx = telemetry.Tx.new(), telemetry.Rx.new()
  local f1, f2 = tx:frame({ alt = 10 }), tx:frame({ alt = 11 })
  t.truthy(rx:accept(f2), "accept newer")
  t.eq(rx:latest().alt, 11)
  t.eq(rx:accept(f1), false, "reject older seq")
  t.eq(rx:latest().alt, 11, "latest unchanged")
  t.eq(rx:accept(f2), false, "reject duplicate seq")
end)

t.test("rx ignores non-telemetry frames", function()
  local rx = telemetry.Rx.new()
  t.eq(rx:accept({ k = "cmd", id = 1 }), false, "not tel")
  t.eq(rx:latest(), nil, "no latest")
end)

t.test("tx stamps a session id that is stable across frames", function()
  local tx = telemetry.Tx.new()
  local f1, f2 = tx:frame({}), tx:frame({})
  t.truthy(f1.sid ~= nil, "sid present")
  t.eq(f1.sid, f2.sid, "same session across frames")
end)

t.test("rx accepts a fresh session after an FCS restart (seq resets, must not be rejected as stale)", function()
  local rx = telemetry.Rx.new()
  rx:accept({ k = "tel", sid = "A", seq = 1,   s = { gndSafety = false } })
  rx:accept({ k = "tel", sid = "A", seq = 500, s = { gndSafety = false } })
  t.eq(rx:latest().gndSafety, false)
  -- FCS reboots: brand new session, seq restarts at 1 -- the whole reason the panel froze until
  -- seq climbed back past the old max. A new session must reset the watermark and be accepted.
  t.truthy(rx:accept({ k = "tel", sid = "B", seq = 1, s = { gndSafety = true } }), "fresh session accepted")
  t.eq(rx:latest().gndSafety, true, "reported state follows the restarted FCS immediately")
end)

t.test("rx still rejects stale/duplicate seq WITHIN a session", function()
  local rx = telemetry.Rx.new()
  rx:accept({ k = "tel", sid = "A", seq = 5, s = { x = 1 } })
  t.eq(rx:accept({ k = "tel", sid = "A", seq = 5, s = { x = 2 } }), false, "duplicate rejected")
  t.eq(rx:accept({ k = "tel", sid = "A", seq = 4, s = { x = 3 } }), false, "older rejected")
  t.eq(rx:latest().x, 1, "kept the first")
end)
