local t = require("tests.framework")
local T = require("fcs.tuning")

t.test("tuning exposes the known-good gains", function()
  t.near(T.gains.hoverDuty, 0.66, 1e-9)
  t.near(T.gains.alt.kd, 0.30, 1e-9)
  t.near(T.gains.yaw.kd, 1.4, 1e-9)
end)
t.test("tuning exposes actuator + safety params", function()
  t.near(T.pwmPeriod, 0.3, 1e-9)
  t.near(T.caps.pitch, 0.2, 1e-9)
  t.eq(T.osc.minChanges, 6)
  t.near(T.dtMax, 0.5, 1e-9)
end)
t.test("tuning exposes the flight profile params", function()
  t.near(T.profile.climbHeight, 5, 1e-9)
  t.near(T.profile.holdTime, 10, 1e-9)
  t.near(T.profile.descendRate, 0.7, 1e-9)
end)
