local t = require("tests.framework")
local Mixer = require("fcs.mixer.level_flight")
t.test("positive yaw fires the +dir pair, zeroes the others", function()
  local d = Mixer.new():mixYaw(0.4)
  t.near(d.YFL, 0.4, 1e-9); t.near(d.YRR, 0.4, 1e-9)
  t.near(d.YFR, 0, 1e-9);   t.near(d.YRL, 0, 1e-9)
end)
t.test("negative yaw fires the -dir pair", function()
  local d = Mixer.new():mixYaw(-0.4)
  t.near(d.YFR, 0.4, 1e-9); t.near(d.YRL, 0.4, 1e-9)
  t.near(d.YFL, 0, 1e-9);   t.near(d.YRR, 0, 1e-9)
end)
t.test("yaw duty clamps to 1", function()
  t.near(Mixer.new():mixYaw(1.5).YFL, 1, 1e-9)
end)
