local t = require("tests.framework")
local cal = require("fcs.io.calibration")

t.test("gate: dominant below floor is too-small", function()
  t.eq(cal.gate(0.001, 0, 0.02, 3), "too-small")
end)
t.test("gate: dominant not beating runner-up by ratio is too-ambiguous", function()
  t.eq(cal.gate(0.20, 0.15, 0.02, 3), "too-ambiguous")   -- 0.20 < 3*0.15
end)
t.test("gate: clear dominant with tiny runner-up is ok", function()
  t.eq(cal.gate(0.40, 0.03, 0.02, 3), "ok")              -- 0.40 > 3*0.03
end)
t.test("gate: zero runner-up above floor is ok", function()
  t.eq(cal.gate(0.40, 0, 0.02, 3), "ok")
end)
t.test("gate: uses module defaults when floor/ratio omitted", function()
  t.eq(cal.gate(0.001, 0), "too-small")
end)
t.test("classifyScalarSign: positive delta -> +1", function()
  local r = cal.classifyScalarSign(0, 3.0)
  t.eq(r.sign, 1); t.eq(r.status, "ok"); t.near(r.magnitude, 3.0, 1e-9)
end)
t.test("classifyScalarSign: negative delta -> -1", function()
  t.eq(cal.classifyScalarSign(1.0, -2.0).sign, -1)
end)
t.test("classifyScalarSign: sub-floor delta is too-small", function()
  t.eq(cal.classifyScalarSign(0, 0.001).status, "too-small")
end)
t.test("classifyGimbalAxis: nose-up on channel 1 in radians", function()
  local r = cal.classifyGimbalAxis({0, 0}, {0.35, 0.01})
  t.eq(r.idx, 1); t.eq(r.sign, 1); t.eq(r.unit, "rad"); t.near(r.scale, 1, 1e-9)
  t.eq(r.status, "ok")
end)
t.test("classifyGimbalAxis: roll on channel 2, negative, in degrees", function()
  local r = cal.classifyGimbalAxis({0, 0}, {0.2, -22.0})
  t.eq(r.idx, 2); t.eq(r.sign, -1); t.eq(r.unit, "deg")
  t.near(r.scale, math.pi/180, 1e-9); t.eq(r.status, "ok")
end)
t.test("classifyGimbalAxis: pitch with 20pct roll bleed still resolves to pitch", function()
  local r = cal.classifyGimbalAxis({0, 0}, {0.40, 0.08})   -- 0.40 vs 0.08 = 5x
  t.eq(r.idx, 1); t.eq(r.sign, 1); t.eq(r.status, "ok")
end)
t.test("classifyGimbalAxis: too-close channels are rejected as too-ambiguous", function()
  local r = cal.classifyGimbalAxis({0, 0}, {0.22, 0.15})   -- 0.22 < 3*0.15
  t.eq(r.status, "too-ambiguous")
end)
t.test("classifyGimbalAxis: no real motion is too-small", function()
  t.eq(cal.classifyGimbalAxis({0, 0}, {0.001, -0.001}).status, "too-small")
end)
local NZ = {front=0, rear=0}
t.test("classifyLateralPair: clean rightward sway sets both signs +", function()
  -- both sensors read + for rightward; yaw: front +, rear - (nose-right)
  local r = cal.classifyLateralPair(NZ, {front=2.0, rear=2.0}, {front=2.0, rear=-2.0})
  t.eq(r.signFront, 1); t.eq(r.signRear, 1); t.eq(r.signYawRate, 1)
  t.eq(r.swayOk, true); t.eq(r.yawOk, true)
end)
t.test("classifyLateralPair: an inverted rear sensor is caught", function()
  -- rear sensor wired inverted: reads - for rightward sway
  local r = cal.classifyLateralPair(NZ, {front=2.0, rear=-2.0}, {front=2.0, rear=2.0})
  t.eq(r.signFront, 1); t.eq(r.signRear, -1)
end)
t.test("classifyLateralPair: yaw contaminated with sway still yields clean yaw sign", function()
  -- nose-right yaw (front +, rear -) plus 30pct common sway drift (+0.6 both)
  local r = cal.classifyLateralPair(NZ, {front=2.0, rear=2.0},
                                        {front=2.6, rear=-1.4})   -- diff=4.0 dominates comm=1.2
  t.eq(r.signYawRate, 1); t.eq(r.yawOk, true)
end)
t.test("classifyLateralPair: a mostly-yaw sway sample is rejected (swayOk false)", function()
  local r = cal.classifyLateralPair(NZ, {front=2.0, rear=-2.0}, {front=2.0, rear=-2.0})
  t.eq(r.swayOk, false)   -- sway sample had no common-mode
end)
