local t = require("tests.framework")
local keymap = require("fcs.input.keymap")

t.test("forMode returns the coupled map for CPL/DCPL, default otherwise", function()
  t.eq(keymap.forMode("CPL"), keymap.coupled, "CPL -> coupled")
  t.eq(keymap.forMode("DCPL"), keymap.coupled, "DCPL -> coupled")
  t.eq(keymap.forMode("PRECISION"), keymap.default, "PRECISION -> default")
  t.eq(keymap.forMode(nil), keymap.default, "nil -> default")
end)

t.test("coupled layout: L-Shift throttle, Space brake, W nose-down, arrows translate", function()
  local h = keymap.resolve(keymap.coupled, { keys.leftShift, keys.space, keys.w, keys.up, keys.left, keys.q, keys.comma })
  t.eq(h.surgeFwd, true, "L-Shift = throttle")
  t.eq(h.surgeBack, true, "Space = brake")
  t.eq(h.pitchDown, true, "W = nose down")
  t.eq(h.fineFwd, true, "Up = slow surge fwd")
  t.eq(h.swayLeft, true, "Left = strafe left")
  t.eq(h.rudderLeft, true, "Q = rudder left")
  t.eq(h.yawLeft, true, "comma = full yaw left")
end)

t.test("MAN pitch flip: Up arrow is now nose-down in the default map", function()
  local h = keymap.resolve(keymap.default, { keys.up })
  t.eq(h.pitchDown, true, "Up -> pitchDown (flipped)")
end)
