local t = require("tests.framework")
local T = require("fcs.tuning")

t.test("tuning exposes the flight-tuned gains", function()
  t.near(T.gains.hoverDuty, 0.35, 1e-9)
  t.near(T.gains.alt.kd, 0.30, 1e-9)
  t.near(T.gains.yaw.kd, 1.4, 1e-9)
end)
t.test("pitch/roll carry a bounded integral to trim the CoM offset", function()
  t.near(T.gains.pitch.ki, 0.08, 1e-9); t.near(T.gains.pitch.iMax, 0.25, 1e-9)
  t.near(T.gains.roll.ki, 0.08, 1e-9); t.near(T.gains.roll.iMin, -0.25, 1e-9)
end)
t.test("heave authority band keeps lift off the rails", function()
  t.near(T.gains.heaveMin, 0.05, 1e-9); t.near(T.gains.heaveMax, 0.85, 1e-9)
end)
t.test("tuning exposes actuator + safety params", function()
  t.near(T.pwmPeriod, 0.3, 1e-9)
  t.near(T.caps.pitch, 0.2, 1e-9)
  t.eq(T.osc.minChanges, 6)
  t.near(T.dtMax, 0.5, 1e-9)
  t.near(T.attLimit, 0.6, 1e-9)
end)
t.test("tuning exposes the flight profile params", function()
  t.near(T.profile.climbHeight, 2, 1e-9)
  t.near(T.profile.climbRate, 0.6, 1e-9)
  t.near(T.profile.holdTime, 10, 1e-9)
  t.near(T.profile.descendRate, 0.7, 1e-9)
  t.near(T.profile.leadCap, 1.0, 1e-9)
end)
