local t = require("tests.framework")
local Mixer = require("fcs.mixer.level_flight")
t.test("pure heave = equal duties, no moment", function()
  local d = Mixer.new():mix({ heave = 0.5, pitch = 0, roll = 0 })
  t.near(d.FL, 0.5, 1e-9); t.near(d.FR, 0.5, 1e-9); t.near(d.RL, 0.5, 1e-9); t.near(d.RR, 0.5, 1e-9)
end)
t.test("nose-up pitch raises front duties, lowers rear", function()
  local d = Mixer.new():mix({ heave = 0.5, pitch = 0.1, roll = 0 })
  t.near(d.FL, 0.6, 1e-9); t.near(d.RL, 0.4, 1e-9)
end)
t.test("duties clamp to [0,1]", function()
  local d = Mixer.new():mix({ heave = 1.0, pitch = 0.5, roll = 0 })
  t.near(d.FL, 1.0, 1e-9); t.near(d.RL, 0.5, 1e-9)
end)
