local t = require("tests.framework")
local Sim = require("tests.sim")
local function cfg() return { mass=4, g=10, fPer=15, inertia=2, armX=1, armZ=1,
  fPerLat=8, yawInertia=8, fMain=20, fFrontal=10 } end
t.test("firing the +right lateral pair sways right (swayVel > 0)", function()
  local s = Sim.new(cfg()); s:setThruster("YFL", true); s:setThruster("YRL", true)
  s:step(0.1); t.truthy(s:sensors().swayVel > 0)
end)
t.test("MAIN thruster surges forward (surgeVel > 0)", function()
  local s = Sim.new(cfg()); s:setThruster("MAIN", true)
  s:step(0.1); t.truthy(s:sensors().surgeVel > 0)
end)
t.test("frontal thrusters brake/reverse (surgeVel < 0)", function()
  local s = Sim.new(cfg()); s:setThruster("FRL", true); s:setThruster("FRR", true)
  s:step(0.1); t.truthy(s:sensors().surgeVel < 0)
end)
t.test("position integrates velocity", function()
  local s = Sim.new(cfg()); s:setThruster("MAIN", true)
  s:step(0.1); s:step(0.1); t.truthy(s:sensors().surgePos > 0)
end)
