local t = require("tests.framework")
local I = require("fcs.bringup.instrument")

t.test("header and formatRow agree on column count", function()
  local ncols = select(2, I.header():gsub(",", ",")) + 1
  local row = I.formatRow({ t=0, dt=0.1, phase="CLIMB", mode="NORMAL", onGround=false, duties={} })
  local nrow = select(2, row:gsub(",", ",")) + 1
  t.eq(nrow, ncols)
end)
t.test("capture snapshots the live duties table so deferred formatRow is immune to later mutation", function()
  -- The control loop reuses/overwrites its duties table each cycle. To move formatRow OFF the hot
  -- path we buffer the raw sample and format at dump time -- which is only safe if the shared duties
  -- reference is snapshotted at capture. This is the correctness guard for that deferral.
  local live = { FL = 0.1, FR = 0.2, RL = 0.3, RR = 0.4 }
  local sample = { t = 1, dt = 0.1, phase = "ENGAGED", mode = "NORMAL", pitch = 0.05, duties = live }
  local rec = I.capture(sample)
  local atCapture = I.formatRow(rec)
  live.FL = 0.99; live.FR = 0.88   -- next cycle overwrites the live duties in place
  t.eq(I.formatRow(rec), atCapture, "captured record's formatRow is unaffected by later duties mutation")
  t.truthy(atCapture:find("0.1000", 1, true), "the FL=0.1 snapshot is preserved for the deferred format")
end)

t.test("Summary computes bob amplitude from HOLD samples", function()
  local s = I.Summary.new()
  s:add({ t=0,   dt=0.1, phase="HOLD", alt=5.0, sp_alt=5, heading=0 })
  s:add({ t=0.1, dt=0.1, phase="HOLD", alt=5.3, sp_alt=5, heading=0 })
  s:add({ t=0.2, dt=0.1, phase="HOLD", alt=4.8, sp_alt=5, heading=0 })
  t.near(s:finalize().bobAmplitude, 0.5, 1e-9)
end)
t.test("Summary tracks per-phase alt error and average Hz", function()
  local s = I.Summary.new()
  s:add({ t=0,   dt=0.2, phase="CLIMB", alt=1.0, sp_alt=1.5, heading=0 })
  s:add({ t=0.2, dt=0.2, phase="CLIMB", alt=2.0, sp_alt=2.0, heading=0 })
  local m = s:finalize()
  t.near(m.errClimb.mean, 0.25, 1e-9); t.near(m.errClimb.max, 0.5, 1e-9)
  t.near(m.hzAvg, 5, 1e-9)
end)
t.test("Summary flags DAMPED and captures touchdown + drift + heading drift", function()
  local s = I.Summary.new()
  s:add({ t=0,   dt=0.1, phase="DESCEND", alt=1,   sp_alt=1,   vSpeed=-0.5, mode="NORMAL", swayPos=0,   surgePos=0,    heading=0 })
  s:add({ t=0.1, dt=0.1, phase="DESCEND", alt=0.5, sp_alt=0.5, vSpeed=-0.3, mode="DAMPED", swayPos=0.4, surgePos=-0.2, heading=0.1 })
  s:add({ t=0.2, dt=0.1, phase="LANDED",  alt=0,   sp_alt=0,   vSpeed=-0.1, mode="NORMAL", swayPos=0.2, surgePos=0,    heading=0.05 })
  local m = s:finalize()
  t.eq(m.damped, true)
  t.near(m.touchdownV, -0.1, 1e-9)
  t.near(m.swayRange, 0.4, 1e-9)
  t.near(m.surgeRange, 0.2, 1e-9)
  t.near(m.headingDrift, 0.1, 1e-9)
end)
t.test("formatSummary produces readable key: value lines", function()
  local s = I.Summary.new(); s:add({ t=0, dt=0.1, phase="HOLD", alt=5, sp_alt=5, heading=0 })
  local out = I.formatSummary(s:finalize())
  t.truthy(out:find("hold_bob_amplitude_blocks:"))
  t.truthy(out:find("loop_hz:"))
end)
