-- tests/test_switchbtn.lua
local t = require("tests.framework")
local Switch = require("ui.basalt.switchbtn")
local BasaltApp = require("ui.basalt.app")

t.test("styleFor maps states to colours (unknown -> disabled)", function()
  local on = Switch.styleFor("on")
  t.eq(on.bg, "green"); t.eq(on.enabled, true)
  local off = Switch.styleFor("off")
  t.eq(off.bg, "red"); t.eq(off.enabled, true)
  local dis = Switch.styleFor("disabled")
  t.eq(dis.bg, "gray"); t.eq(dis.enabled, false)
  local unknown = Switch.styleFor("bogus")
  t.eq(unknown.bg, "gray"); t.eq(unknown.enabled, false, "unknown falls back to disabled")
end)

-- CONSTRUCTION PROBE: real Basalt, make a switch, drive it through states, render one frame.
t.test("make() builds a switch button and set() applies states without error", function()
  local basalt = BasaltApp.ensureBasalt()
  local frame = basalt.createFrame()
  local sw = Switch.make(frame, { x = 2, y = 2, width = 6, height = 1, text = "ENG" })
  t.truthy(sw.button, "returns the underlying button")
  local ok = pcall(function()
    sw.set("on"); sw.set("off"); sw.set("disabled")
  end)
  t.truthy(ok, "set() through all states does not error")
  local okr, err = pcall(function() basalt.update("timer", -1) end)
  t.truthy(okr, "basalt.update should not error: " .. tostring(err))
end)
