local t = require("tests.framework")
local Sim = require("tests.sim")
local function cfg() return { mass=4, g=10, fPer=15, inertia=2, armX=1, armZ=1, fPerLat=8, yawInertia=2 } end
t.test("firing the +yaw pair yaws nose-right (yawRate > 0)", function()
  local s = Sim.new(cfg())
  s:setThruster("YFL", true); s:setThruster("YRR", true)
  s:step(0.1)
  t.truthy(s:sensors().yawRate > 0)
end)
t.test("firing the -yaw pair yaws nose-left (yawRate < 0)", function()
  local s = Sim.new(cfg())
  s:setThruster("YFR", true); s:setThruster("YRL", true)
  s:step(0.1)
  t.truthy(s:sensors().yawRate < 0)
end)
t.test("heading integrates yawRate", function()
  local s = Sim.new(cfg())
  s:setThruster("YFL", true); s:setThruster("YRR", true)
  s:step(0.1); s:step(0.1)
  t.truthy(s:sensors().heading > 0)
end)
