local t = require("tests.framework")
local H = require("tools.hover_test")
t.test("hover_test module loads and exposes run()", function()
  t.eq(type(H.run), "function")
end)
t.test("hover_test exposes buildLoop() for reuse by tools/flight.lua", function()
  t.eq(type(H.buildLoop), "function")
end)
