local t = require("tests.framework")
local cal = require("fcs.io.calibration")

t.test("gate: dominant below floor is too-small", function()
  t.eq(cal.gate(0.001, 0, 0.02, 3), "too-small")
end)
t.test("gate: dominant not beating runner-up by ratio is too-ambiguous", function()
  t.eq(cal.gate(0.20, 0.15, 0.02, 3), "too-ambiguous")   -- 0.20 < 3*0.15
end)
t.test("gate: clear dominant with tiny runner-up is ok", function()
  t.eq(cal.gate(0.40, 0.03, 0.02, 3), "ok")              -- 0.40 > 3*0.03
end)
t.test("gate: zero runner-up above floor is ok", function()
  t.eq(cal.gate(0.40, 0, 0.02, 3), "ok")
end)
t.test("gate: uses module defaults when floor/ratio omitted", function()
  t.eq(cal.gate(0.001, 0), "too-small")
end)
t.test("classifyScalarSign: positive delta -> +1", function()
  local r = cal.classifyScalarSign(0, 3.0)
  t.eq(r.sign, 1); t.eq(r.status, "ok"); t.near(r.magnitude, 3.0, 1e-9)
end)
t.test("classifyScalarSign: negative delta -> -1", function()
  t.eq(cal.classifyScalarSign(1.0, -2.0).sign, -1)
end)
t.test("classifyScalarSign: sub-floor delta is too-small", function()
  t.eq(cal.classifyScalarSign(0, 0.001).status, "too-small")
end)
t.test("classifyGimbalAxis: nose-up on channel 1 in radians", function()
  local r = cal.classifyGimbalAxis({0, 0}, {0.35, 0.01})
  t.eq(r.idx, 1); t.eq(r.sign, 1); t.eq(r.unit, "rad"); t.near(r.scale, 1, 1e-9)
  t.eq(r.status, "ok")
end)
t.test("classifyGimbalAxis: roll on channel 2, negative, in degrees", function()
  local r = cal.classifyGimbalAxis({0, 0}, {0.2, -22.0})
  t.eq(r.idx, 2); t.eq(r.sign, -1); t.eq(r.unit, "deg")
  t.near(r.scale, math.pi/180, 1e-9); t.eq(r.status, "ok")
end)
t.test("classifyGimbalAxis: pitch with 20pct roll bleed still resolves to pitch", function()
  local r = cal.classifyGimbalAxis({0, 0}, {0.40, 0.08})   -- 0.40 vs 0.08 = 5x
  t.eq(r.idx, 1); t.eq(r.sign, 1); t.eq(r.status, "ok")
end)
t.test("classifyGimbalAxis: too-close channels are rejected as too-ambiguous", function()
  local r = cal.classifyGimbalAxis({0, 0}, {0.22, 0.15})   -- 0.22 < 3*0.15
  t.eq(r.status, "too-ambiguous")
end)
t.test("classifyGimbalAxis: no real motion is too-small", function()
  t.eq(cal.classifyGimbalAxis({0, 0}, {0.001, -0.001}).status, "too-small")
end)
local NZ = {front=0, rear=0}
t.test("classifyLateralPair: clean rightward sway sets both signs +", function()
  -- both sensors read + for rightward; yaw: front +, rear - (nose-right)
  local r = cal.classifyLateralPair(NZ, {front=2.0, rear=2.0}, {front=2.0, rear=-2.0})
  t.eq(r.signFront, 1); t.eq(r.signRear, 1); t.eq(r.signYawRate, 1)
  t.eq(r.swayOk, true); t.eq(r.yawOk, true)
end)
t.test("classifyLateralPair: an inverted rear sensor is caught", function()
  -- rear sensor wired inverted: reads - for rightward sway
  local r = cal.classifyLateralPair(NZ, {front=2.0, rear=-2.0}, {front=2.0, rear=2.0})
  t.eq(r.signFront, 1); t.eq(r.signRear, -1)
end)
t.test("classifyLateralPair: yaw contaminated with sway still yields clean yaw sign", function()
  -- nose-right yaw (front +, rear -) plus 30pct common sway drift (+0.6 both)
  local r = cal.classifyLateralPair(NZ, {front=2.0, rear=2.0},
                                        {front=2.6, rear=-1.4})   -- diff=4.0 (well above floor)
  t.eq(r.signYawRate, 1); t.eq(r.yawOk, true)
end)
t.test("classifyLateralPair: a mostly-yaw sway sample is rejected (swayOk false)", function()
  local r = cal.classifyLateralPair(NZ, {front=2.0, rear=-2.0}, {front=2.0, rear=-2.0})
  t.eq(r.swayOk, false)   -- sway sample had no common-mode
end)
t.test("classifyLateralPair: off-center-pivot yaw with large common-mode is still accepted", function()
  -- plunger yaw pivots off-center: front swings far more than rear, so the sample carries
  -- big common-mode translation. The differential (front-rear) still captures the rotation,
  -- so this MUST be accepted (the old ratio gate wrongly rejected it as too-ambiguous).
  local r = cal.classifyLateralPair(NZ, {front=2.0, rear=2.0}, {front=3.0, rear=1.0})
  t.eq(r.yawOk, true); t.eq(r.signYawRate, 1)   -- diff=2 (>floor), comm=4
end)
t.test("classifyLateralPair: nose-left off-center yaw gives signYawRate -1", function()
  local r = cal.classifyLateralPair(NZ, {front=2.0, rear=2.0}, {front=1.0, rear=3.0})
  t.eq(r.yawOk, true); t.eq(r.signYawRate, -1)  -- diff=-2
end)
t.test("classifyLateralPair: pure translation during the yaw step is rejected (no rotation)", function()
  -- yaw sample is common motion with no differential -> diff ~ 0 -> too-small
  local r = cal.classifyLateralPair(NZ, {front=2.0, rear=2.0}, {front=1.5, rear=1.5})
  t.eq(r.yawOk, false)
end)
t.test("detectHeadingScale: 90 deg rotation detected as degrees, sign +", function()
  local r = cal.detectHeadingScale(0, 90)
  t.eq(r.unit, "deg"); t.near(r.scale, math.pi/180, 1e-9); t.eq(r.sign, 1); t.eq(r.status, "ok")
end)
t.test("detectHeadingScale: ~1.5 rad rotation detected as radians", function()
  local r = cal.detectHeadingScale(0, 1.5)
  t.eq(r.unit, "rad"); t.near(r.scale, 1, 1e-9); t.eq(r.sign, 1)
end)
t.test("detectHeadingScale: leftward rotation gives sign -1", function()
  t.eq(cal.detectHeadingScale(0, -85).sign, -1)
end)
t.test("computeHeightOffset: zeroes rest altitude including baro-thruster offset", function()
  t.near(cal.computeHeightOffset(64, 3), -67, 1e-9)
end)
t.test("computeGroundThreshold: adds default margin", function()
  t.near(cal.computeGroundThreshold(0.5), 1.0, 1e-9)
end)
