-- tests/test_nav.lua
local t = require("tests.framework")
local M = require("ui.basalt.nav")

t.test("new(root) seeds stack with root at bottom", function()
  local n = M.new("emc")
  t.eq(n:top(), "emc", "top() returns the root screen")
  t.eq(n:depth(), 1, "depth() is 1 at root")
  t.eq(n:canBack(), false, "canBack() is false at root")
end)

t.test("push() adds screens to stack", function()
  local n = M.new("emc")
  n:push("bitconfig")
  n:push("tuning")
  t.eq(n:top(), "tuning", "top() returns the most recently pushed screen")
  t.eq(n:depth(), 3, "depth() includes root and all pushed screens")
  t.eq(n:canBack(), true, "canBack() is true when depth > 1")
end)

t.test("pop() removes top screen and returns new top", function()
  local n = M.new("emc")
  n:push("bitconfig")
  n:push("tuning")
  local newTop = n:pop()
  t.eq(newTop, "bitconfig", "pop() returns the new top screen")
  t.eq(n:top(), "bitconfig", "top() reflects the popped stack")
  local newTop2 = n:pop()
  t.eq(newTop2, "emc", "pop() returns emc after removing bitconfig")
  t.eq(n:top(), "emc", "top() returns root after popping all pushed screens")
  t.eq(n:canBack(), false, "canBack() is false when back at root")
end)

t.test("pop() at root is a NO-OP", function()
  local n = M.new("emc")
  local result = n:pop()
  t.eq(result, "emc", "pop() at root returns current top (no-op)")
  t.eq(n:top(), "emc", "top() unchanged after pop() at root")
  t.eq(n:depth(), 1, "depth() unchanged after pop() at root")
end)
