local t = require("tests.framework")
local Translate = require("fcs.control.translate")
t.test("commands positive force toward a positive position error", function()
  local c = Translate.new({ kp = 1, ki = 0, kd = 0 })
  t.near(c:update(2, 0, 0, 0.1), 2, 1e-9)
end)
t.test("damps proportionally to velocity", function()
  local c = Translate.new({ kp = 0, ki = 0, kd = 0.5 })
  t.near(c:update(0, 0, 3.0, 0.1), -1.5, 1e-9)
end)
t.test("integral accumulates and clamps", function()
  local c = Translate.new({ kp = 0, ki = 1, kd = 0, iMax = 0.5 })
  for _ = 1, 50 do c:update(1, 0, 0, 0.1) end
  t.near(c:update(1, 0, 0, 0), 0.5, 1e-9)
end)
