local t = require("tests.framework")
local cal = require("fcs.io.calibration")

t.test("gate: dominant below floor is too-small", function()
  t.eq(cal.gate(0.001, 0, 0.02, 3), "too-small")
end)
t.test("gate: dominant not beating runner-up by ratio is too-ambiguous", function()
  t.eq(cal.gate(0.20, 0.15, 0.02, 3), "too-ambiguous")   -- 0.20 < 3*0.15
end)
t.test("gate: clear dominant with tiny runner-up is ok", function()
  t.eq(cal.gate(0.40, 0.03, 0.02, 3), "ok")              -- 0.40 > 3*0.03
end)
t.test("gate: zero runner-up above floor is ok", function()
  t.eq(cal.gate(0.40, 0, 0.02, 3), "ok")
end)
t.test("gate: uses module defaults when floor/ratio omitted", function()
  t.eq(cal.gate(0.001, 0), "too-small")
end)
t.test("classifyScalarSign: positive delta -> +1", function()
  local r = cal.classifyScalarSign(0, 3.0)
  t.eq(r.sign, 1); t.eq(r.status, "ok"); t.near(r.magnitude, 3.0, 1e-9)
end)
t.test("classifyScalarSign: negative delta -> -1", function()
  t.eq(cal.classifyScalarSign(1.0, -2.0).sign, -1)
end)
t.test("classifyScalarSign: sub-floor delta is too-small", function()
  t.eq(cal.classifyScalarSign(0, 0.001).status, "too-small")
end)
